[project]
name = 'Peer-to-Peer-Decentralized-VPN-Marketplace'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.achievement-registry]
path = 'contracts/achievement-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.identity-manager]
path = 'contracts/identity-manager.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.escrow-manager]
path = 'contracts/escrow-manager.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
